server:
  port: 8080
  servlet:
    context-path: /mj
logging:
  level:
    ROOT: info
    com.github.novicezk.midjourney: debug
knife4j:
  enable: true
  openapi:
    title: Midjourney Proxy API文档
    description: 代理 MidJourney 的discord频道，实现api形式调用AI绘图
    concat: novicezk
    url: https://github.com/novicezk/midjourney-proxy
    version: v2.6.3
    terms-of-service-url: https://github.com/novicezk/midjourney-proxy
    group:
      api:
        group-name: API
        api-rule: package
        api-rule-resources: null
filePath:
#配置代理 防止连接超时
mj:
  proxy:
    host: 127.0.0.1
    port: 7890
#配置合法跨域地址
CROS_ALLOWED_ORIGINS: http://localhost:1002,http://localhost:5666,http://localhost:6039,http://104.244.93.11:6013